### PR TITLE
feat: Add toggle for `--user uid:gid` in `opensafely exec`

### PR DESCRIPTION
**Pull request by StevenMaude**
As the `exec` option stands, it doesn't work with rootless Docker.

See https://github.com/opensafely-core/opensafely-cli/issues/149#issuecomment-1293513246

### CODE REVIEW

**Comment by StevenMaude** [comment]
I'm not sure if this is the best solution, but it works for me.

**Comment by evansd** [comment]
Hi @StevenMaude, I'd like to understand a bit more about what's going on here before we make any changes.

Can you confirm the ownership and permissions of the file created with your patch in place? Is it owned by root or by you (or something else)?

In terms of immediately unblocking yourself, you can emulate the current behaviour of `opensafely exec` with a tiny shell script:
```sh
#!/bin/sh
image="$1"
shift 1
exec docker run --rm --volume="$PWD:/workspace" --user "$(id -u):$(id -g)" \
  "ghcr.io/opensafely-core/$image" "$@"
```

If you remove the `--user` argument from that it should do what you want.

**Comment by lucyb** [comment]
Is this PR still needed or should it be closed now?

**Comment by StevenMaude** [comment]
I'll close because you can at least configure the UID:GID in `opensafely exec`.

I think this will still need a wrapper or similar on my own install because there may be cases — like when writing a script — where:

* the default UID and GID won't work because of rootless Docker
* but I don't want to actually override the UID:GID in the script, because it might be intended for others or CI to run

But that's fine; I'll look into it.

**Pull request closed without merging**
