### PR TITLE
Add basic info command

### PR DESCRIPTION
**Pull request by bloodearnest**
The goal is to help users be more aware of their docker resources.

### CODE REVIEW

**Review by ghickman — APPROVED** [review]

**Comment by sebbacon** [comment]
Nice. Worth highlighting in the documentation somewhere too? 

I'm thinking maybe in the "running opensafely" section [here](https://docs.opensafely.org/getting-started/#3-setup-the-required-software), for example.  Or maybe in the [bit about running actions locally](https://docs.opensafely.org/actions-pipelines/#running-your-code-locally), or [the tips about writing performant code](https://docs.opensafely.org/memory-efficient-working/)? @StevenMaude thoughts on the matter appreciated.

Either way, don't forget about the "platform news" as this is a nice thing to advertise quietly, at least

**Comment by bloodearnest** [comment]
This PR was prompted by writing the documentation. See https://github.com/opensafely/documentation/pull/928.

**Comment by sebbacon** [comment]
Great. I think it's probably worth cross-linking between that documentation and elsewhere though - @StevenMaude what do you think?

It's very useful and most people won't read the "how to use the cli tool page" as much as they'll read the "dealing with memory problems" type page, I think?

**Comment by bloodearnest** [comment]
If you look at the PR, we do cross link

**Comment by bloodearnest** [comment]
Can we add comments on additional links to that PR?

**Pull request merged**
